-- Schema for MyBatis version of backend (previously auto-generated by Hibernate ddl-auto=update)
-- Statements are idempotent so this file can safely run on every application startup
-- (spring.sql.init.mode=always in application.properties).

CREATE TABLE IF NOT EXISTS tbl_member (
                                          email    VARCHAR(100) NOT NULL,
    pw       VARCHAR(100) NOT NULL,
    nickname VARCHAR(50)  NOT NULL,
    social   BOOLEAN      NOT NULL DEFAULT FALSE,
    PRIMARY KEY (email)
    );

CREATE TABLE IF NOT EXISTS tbl_member_role (
                                               member_email VARCHAR(100) NOT NULL,
    role_name    VARCHAR(20)  NOT NULL,
    CONSTRAINT fk_member_role_email FOREIGN KEY (member_email) REFERENCES tbl_member (email)
    );

-- LDH 시작
CREATE TABLE IF NOT EXISTS tbl_member_social (
                                                 id             BIGINT AUTO_INCREMENT,
    member_email   VARCHAR(100) NOT NULL,
    provider       VARCHAR(20)  NOT NULL,
    provider_id    VARCHAR(100) NOT NULL,
    provider_email VARCHAR(100),
    connected_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_member_social_provider (provider, provider_id),
    UNIQUE KEY uk_member_social_member_provider (member_email, provider),
    CONSTRAINT fk_member_social_email FOREIGN KEY (member_email) REFERENCES tbl_member (email)
    );

CREATE TABLE IF NOT EXISTS tbl_member_refresh_token (
                                                        id BIGINT AUTO_INCREMENT,
    member_email VARCHAR(100) NOT NULL,
    session_id VARCHAR(36) NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at DATETIME NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    used_at DATETIME,
    user_agent VARCHAR(255),
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_member_refresh_token_hash (token_hash),
    INDEX idx_member_refresh_token_session_id (session_id),
    INDEX idx_member_refresh_token_member_email (member_email),
    CONSTRAINT fk_member_refresh_token_member FOREIGN KEY (member_email) REFERENCES tbl_member (email)
    );
-- LDH 끝

-- HYH
CREATE TABLE IF NOT EXISTS tbl_baby_info (
    baby_no BIGINT AUTO_INCREMENT,
    email VARCHAR(100) NOT NULL,
    baby_name VARCHAR(100) NOT NULL,
    birth_date DATE,
    gender VARCHAR(100) NOT NULL,
    profile_image_file_name VARCHAR(500),
    blood_type VARCHAR(100),
    birth_week_count INT,
    birth_weight DECIMAL(5,2),
    birth_height DECIMAL(5,2),
    head_circumference DECIMAL(5,2),
    reg_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (baby_no),
    CONSTRAINT fk_baby_info FOREIGN KEY (email) REFERENCES tbl_member (email)
    );

CREATE TABLE IF NOT EXISTS tbl_baby_grow_info (
    baby_grow_no BIGINT AUTO_INCREMENT,
    baby_no BIGINT NOT NULL,
    measured_date DATE NOT NULL,
    weight DECIMAL(5,2),
    height DECIMAL(5,2),
    reg_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (baby_grow_no),
    CONSTRAINT fk_baby_grow_info FOREIGN KEY (baby_no) REFERENCES tbl_baby_info (baby_no)
    );

CREATE TABLE IF NOT EXISTS tbl_growth_percentile (
    percentile_no BIGINT AUTO_INCREMENT,
    age_month INT NOT NULL,
    gender VARCHAR(10) NOT NULL,
    avg_weight_kg DECIMAL(5,2) NOT NULL,
    avg_height_cm DECIMAL(5,2) NOT NULL,
    PRIMARY KEY (percentile_no),
    CONSTRAINT uq_growth_percentile UNIQUE (age_month, gender)
    );

INSERT INTO tbl_growth_percentile (age_month, gender, avg_weight_kg, avg_height_cm)
SELECT t.age_month, t.gender, t.avg_weight_kg, t.avg_height_cm
FROM (
         SELECT 0 AS age_month, '남자' AS gender, 3.3 AS avg_weight_kg, 49.9 AS avg_height_cm
         UNION ALL SELECT 3, '남자', 6.4, 61.4
         UNION ALL SELECT 6, '남자', 7.9, 67.6
         UNION ALL SELECT 9, '남자', 8.9, 72.0
         UNION ALL SELECT 12, '남자', 9.6, 75.7
         UNION ALL SELECT 15, '남자', 10.3, 79.1
         UNION ALL SELECT 18, '남자', 10.9, 82.3
         UNION ALL SELECT 21, '남자', 11.5, 85.1
         UNION ALL SELECT 24, '남자', 12.2, 87.8
         UNION ALL SELECT 27, '남자', 12.7, 89.6
         UNION ALL SELECT 30, '남자', 13.3, 91.9
         UNION ALL SELECT 33, '남자', 13.8, 94.1
         UNION ALL SELECT 36, '남자', 14.3, 96.1
         UNION ALL SELECT 0, '여자', 3.2, 49.1
         UNION ALL SELECT 3, '여자', 5.8, 59.8
         UNION ALL SELECT 6, '여자', 7.3, 65.7
         UNION ALL SELECT 9, '여자', 8.2, 70.1
         UNION ALL SELECT 12, '여자', 8.9, 74.0
         UNION ALL SELECT 15, '여자', 9.6, 77.5
         UNION ALL SELECT 18, '여자', 10.2, 80.7
         UNION ALL SELECT 21, '여자', 10.9, 83.7
         UNION ALL SELECT 24, '여자', 11.5, 86.4
         UNION ALL SELECT 27, '여자', 12.1, 88.3
         UNION ALL SELECT 30, '여자', 12.7, 90.7
         UNION ALL SELECT 33, '여자', 13.3, 92.9
         UNION ALL SELECT 36, '여자', 13.9, 95.1
     ) t
WHERE (SELECT COUNT(*) FROM tbl_growth_percentile) = 0;

CREATE TABLE IF NOT EXISTS tbl_vaccine_schedule (
    schedule_no BIGINT AUTO_INCREMENT,
    vaccine_name VARCHAR(100) NOT NULL,
    dose_label VARCHAR(20) NOT NULL,
    recommended_month INT NOT NULL,
    display_order INT NOT NULL,
    PRIMARY KEY (schedule_no)
    );

INSERT INTO tbl_vaccine_schedule (vaccine_name, dose_label, recommended_month, display_order)
SELECT t.vaccine_name, t.dose_label, t.recommended_month, t.display_order
FROM (
         SELECT 'B형간염' AS vaccine_name, '1차' AS dose_label, 0 AS recommended_month, 1 AS display_order
         UNION ALL SELECT 'BCG(결핵)', '1회', 1, 2
         UNION ALL SELECT 'B형간염', '2차', 1, 3
         UNION ALL SELECT 'DTaP', '1차', 2, 4
         UNION ALL SELECT '폴리오', '1차', 2, 5
         UNION ALL SELECT 'DTaP', '2차', 4, 6
         UNION ALL SELECT '폴리오', '2차', 4, 7
         UNION ALL SELECT 'B형간염', '3차', 6, 8
         UNION ALL SELECT 'DTaP', '3차', 6, 9
         UNION ALL SELECT '폴리오', '3차', 6, 10
         UNION ALL SELECT 'MMR', '1차', 12, 11
         UNION ALL SELECT '수두', '1회', 12, 12
     ) AS t
WHERE (SELECT COUNT(*) FROM tbl_vaccine_schedule) = 0;

CREATE TABLE IF NOT EXISTS tbl_baby_vaccination (
    vaccination_no BIGINT AUTO_INCREMENT,
    baby_no BIGINT NOT NULL,
    schedule_no BIGINT,
    vaccine_name VARCHAR(100) NOT NULL,
    dose_label VARCHAR(20),
    recommended_month INT,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    completed_date DATE,
    hospital_name VARCHAR(100),
    is_custom BOOLEAN NOT NULL DEFAULT FALSE,
    reg_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (vaccination_no),
    CONSTRAINT fk_baby_vaccination_baby FOREIGN KEY (baby_no) REFERENCES tbl_baby_info (baby_no),
    CONSTRAINT fk_baby_vaccination_schedule FOREIGN KEY (schedule_no) REFERENCES tbl_vaccine_schedule (schedule_no)
    );





-- KYI - 가계부 내역
CREATE TABLE IF NOT EXISTS tbl_ledger (
    lno      BIGINT AUTO_INCREMENT,
    email    VARCHAR(100) NOT NULL,
    type     VARCHAR(20)  NOT NULL,
    category VARCHAR(30)  NOT NULL,
    amount   INT          NOT NULL,
    memo     VARCHAR(500),
    tx_date  DATE         NOT NULL,
    reg_time DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (lno),
    CONSTRAINT fk_ledger_email FOREIGN KEY (email) REFERENCES tbl_member (email),
    INDEX idx_ledger_email_date (email, tx_date)
);

-- KYI - 가계부 브리핑 설정
CREATE TABLE IF NOT EXISTS tbl_ledger_setting (
    email                    VARCHAR(100) NOT NULL,
    briefing_day             INT,
    last_briefing_cycle_start DATE,
    PRIMARY KEY (email),
    CONSTRAINT fk_ledger_setting_email FOREIGN KEY (email) REFERENCES tbl_member (email)
);

-- KYI - 베이비시터 프로필
CREATE TABLE IF NOT EXISTS tbl_babysitter_profile (
    email          VARCHAR(100) NOT NULL,
    name           VARCHAR(50)  NOT NULL,
    career_years   INT          NOT NULL DEFAULT 0,
    region         VARCHAR(100),
    available_time VARCHAR(255),
    hourly_rate    INT,
    intro          VARCHAR(1000),
    status         VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    reg_time       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_time       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (email),
    CONSTRAINT fk_babysitter_profile_email FOREIGN KEY (email) REFERENCES tbl_member (email),
    INDEX idx_babysitter_profile_region (region)
);

ALTER TABLE tbl_babysitter_profile ADD COLUMN IF NOT EXISTS profile_image_file_name VARCHAR(500) NULL;

-- KYI - 베이비시터 가능 요일/시간대
CREATE TABLE IF NOT EXISTS tbl_babysitter_availability (
    email       VARCHAR(100) NOT NULL,
    day_of_week VARCHAR(10)  NOT NULL,
    time_slot   VARCHAR(10)  NOT NULL,
    PRIMARY KEY (email, day_of_week, time_slot),
    CONSTRAINT fk_babysitter_availability_email FOREIGN KEY (email) REFERENCES tbl_babysitter_profile (email)
);

-- KYI - 부모(사용자) 내 동네 설정
CREATE TABLE IF NOT EXISTS tbl_babysitter_parent_location (
    email  VARCHAR(100) NOT NULL,
    region VARCHAR(100) NOT NULL,
    PRIMARY KEY (email),
    CONSTRAINT fk_babysitter_parent_location_email FOREIGN KEY (email) REFERENCES tbl_member (email)
);

-- KYI - 베이비시터 픽(찜)
CREATE TABLE IF NOT EXISTS tbl_babysitter_pick (
    pick_no      BIGINT AUTO_INCREMENT,
    sitter_email VARCHAR(100) NOT NULL,
    picker_email VARCHAR(100) NOT NULL,
    reg_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (pick_no),
    CONSTRAINT fk_babysitter_pick_sitter FOREIGN KEY (sitter_email) REFERENCES tbl_babysitter_profile (email),
    CONSTRAINT fk_babysitter_pick_picker FOREIGN KEY (picker_email) REFERENCES tbl_member (email),
    CONSTRAINT uq_babysitter_pick UNIQUE (sitter_email, picker_email)
);

-- KYI - 베이비시터 요청(선정)
CREATE TABLE IF NOT EXISTS tbl_babysitter_request (
    request_no   BIGINT AUTO_INCREMENT,
    sitter_email VARCHAR(100) NOT NULL,
    parent_email VARCHAR(100) NOT NULL,
    request_date DATE         NOT NULL,
    time_slot    VARCHAR(10)  NOT NULL,
    message      VARCHAR(500),
    status       VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    reg_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (request_no),
    CONSTRAINT fk_babysitter_request_sitter FOREIGN KEY (sitter_email) REFERENCES tbl_babysitter_profile (email),
    CONSTRAINT fk_babysitter_request_parent FOREIGN KEY (parent_email) REFERENCES tbl_member (email),
    INDEX idx_babysitter_request_sitter (sitter_email, status),
    INDEX idx_babysitter_request_parent (parent_email, status)
);

-- KYI - 베이비시터 후기 (요청 1건당 후기 1개)
CREATE TABLE IF NOT EXISTS tbl_babysitter_review (
    review_no    BIGINT AUTO_INCREMENT,
    request_no   BIGINT       NOT NULL,
    sitter_email VARCHAR(100) NOT NULL,
    writer_email VARCHAR(100) NOT NULL,
    rating       INT          NOT NULL,
    content      VARCHAR(500),
    reg_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (review_no),
    CONSTRAINT fk_babysitter_review_request FOREIGN KEY (request_no) REFERENCES tbl_babysitter_request (request_no),
    CONSTRAINT fk_babysitter_review_sitter FOREIGN KEY (sitter_email) REFERENCES tbl_babysitter_profile (email),
    CONSTRAINT fk_babysitter_review_writer FOREIGN KEY (writer_email) REFERENCES tbl_member (email),
    UNIQUE KEY uq_babysitter_review_request (request_no)
);

-- KYI - 커뮤니티 게시글
CREATE TABLE IF NOT EXISTS tbl_community_post (
    post_no       BIGINT AUTO_INCREMENT,
    writer_email  VARCHAR(100)  NOT NULL,
    nickname      VARCHAR(50)   NOT NULL,
    title         VARCHAR(200)  NOT NULL,
    content       TEXT          NOT NULL,
    ai_summary    TEXT,
    view_count    INT           NOT NULL DEFAULT 0,
    comment_count INT           NOT NULL DEFAULT 0,
    del_flag      BOOLEAN       NOT NULL DEFAULT FALSE,
    reg_time      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_time      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (post_no),
    CONSTRAINT fk_community_post_email FOREIGN KEY (writer_email) REFERENCES tbl_member (email)
);

-- KYI - 커뮤니티 게시글 첨부파일
CREATE TABLE IF NOT EXISTS tbl_community_post_image (
    image_no  BIGINT AUTO_INCREMENT,
    post_no   BIGINT       NOT NULL,
    file_name VARCHAR(300) NOT NULL,
    video     BOOLEAN      NOT NULL DEFAULT FALSE,
    ord       INT          NOT NULL DEFAULT 0,
    PRIMARY KEY (image_no),
    CONSTRAINT fk_community_post_image_post FOREIGN KEY (post_no) REFERENCES tbl_community_post (post_no)
);

-- KYI - 커뮤니티 댓글/대댓글
CREATE TABLE IF NOT EXISTS tbl_community_comment (
    comment_no        BIGINT AUTO_INCREMENT,
    post_no           BIGINT        NOT NULL,
    writer_email      VARCHAR(100)  NOT NULL,
    nickname          VARCHAR(50)   NOT NULL,
    parent_comment_no BIGINT,
    content           VARCHAR(1000) NOT NULL,
    del_flag          BOOLEAN       NOT NULL DEFAULT FALSE,
    reg_time          DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_time          DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (comment_no),
    CONSTRAINT fk_community_comment_post FOREIGN KEY (post_no) REFERENCES tbl_community_post (post_no),
    CONSTRAINT fk_community_comment_email FOREIGN KEY (writer_email) REFERENCES tbl_member (email),
    CONSTRAINT fk_community_comment_parent FOREIGN KEY (parent_comment_no) REFERENCES tbl_community_comment (comment_no)
);

-- KYI - 커뮤니티 댓글 첨부파일
CREATE TABLE IF NOT EXISTS tbl_community_comment_image (
    image_no   BIGINT AUTO_INCREMENT,
    comment_no BIGINT       NOT NULL,
    file_name  VARCHAR(300) NOT NULL,
    video      BOOLEAN      NOT NULL DEFAULT FALSE,
    ord        INT          NOT NULL DEFAULT 0,
    PRIMARY KEY (image_no),
    CONSTRAINT fk_community_comment_image_comment FOREIGN KEY (comment_no) REFERENCES tbl_community_comment (comment_no)
);
-- KYI 끝

-- LMJ
CREATE TABLE IF NOT EXISTS tbl_allergy_ingredient (
    ingredientNo BIGINT AUTO_INCREMENT,
    ingredientName VARCHAR(100) NOT NULL,
    PRIMARY KEY (ingredientNo)
);

CREATE TABLE IF NOT EXISTS tbl_baby_custom_allergy (
    customAllergyNo BIGINT AUTO_INCREMENT,
    babyNo BIGINT NOT NULL,
    ingredientName VARCHAR(100) NOT NULL,
    regTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (customAllergyNo),
    CONSTRAINT fk_custom_allergy_baby FOREIGN KEY (babyNo) REFERENCES tbl_baby_info (baby_no)
);

CREATE TABLE IF NOT EXISTS tbl_baby_allergy_check (
    checkNo BIGINT AUTO_INCREMENT,
    babyNo BIGINT NOT NULL,
    imageFileName VARCHAR(500),
    ocrRawText VARCHAR(2000),
    detectedAllergens VARCHAR(500),
    detectedCustom VARCHAR(500),
    regTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (checkNo),
    CONSTRAINT fk_allergy_check_baby FOREIGN KEY (babyNo) REFERENCES tbl_baby_info (baby_no)
);

CREATE TABLE IF NOT EXISTS tbl_recipe_recommend (
    recommendNo BIGINT AUTO_INCREMENT,
    checkNo BIGINT NOT NULL,
    productType VARCHAR(20) NOT NULL,
    recommendedRecipe VARCHAR(3000),
    regTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (recommendNo),
    CONSTRAINT fk_recipe_recommend_check FOREIGN KEY (checkNo) REFERENCES tbl_baby_allergy_check (checkNo)
);

INSERT INTO tbl_allergy_ingredient (ingredientName) VALUES
    ('알류(가금류)'),
    ('우유'),
    ('메밀'),
    ('땅콩'),
    ('대두'),
    ('밀'),
    ('고등어'),
    ('게'),
    ('새우'),
    ('돼지고기'),
    ('복숭아'),
    ('토마토'),
    ('아황산류'),
    ('호두'),
    ('닭고기'),
    ('쇠고기'),
    ('오징어'),
    ('조개류(굴, 전복, 홍합 포함)'),
    ('잣');

-- =========================================================
-- YSJ - 퀘스트 (DAILY / URGENT)
-- =========================================================

CREATE TABLE IF NOT EXISTS tbl_quest (
    quest_id     BIGINT AUTO_INCREMENT,
    title        VARCHAR(200) NOT NULL,
    description  TEXT,
    type         VARCHAR(20)  NOT NULL,              -- DAILY | URGENT
    difficulty   VARCHAR(20)  NOT NULL DEFAULT 'MEDIUM',
    theme        VARCHAR(50)  NULL,
    reward       INT          NOT NULL DEFAULT 0,
    urgency      INT          NOT NULL DEFAULT 1,
    due_days     INT          NOT NULL DEFAULT 1,
    active       BOOLEAN      NOT NULL DEFAULT TRUE,
    PRIMARY KEY (quest_id),
    INDEX idx_quest_type_active (type, active)
);

-- 구DB 호환: 없는 컬럼만 추가
ALTER TABLE tbl_quest ADD COLUMN IF NOT EXISTS difficulty  VARCHAR(20) NOT NULL DEFAULT 'MEDIUM';
ALTER TABLE tbl_quest ADD COLUMN IF NOT EXISTS theme       VARCHAR(50) NULL;
ALTER TABLE tbl_quest ADD COLUMN IF NOT EXISTS reward      INT NOT NULL DEFAULT 0;
ALTER TABLE tbl_quest ADD COLUMN IF NOT EXISTS urgency     INT NOT NULL DEFAULT 1;
ALTER TABLE tbl_quest ADD COLUMN IF NOT EXISTS due_days    INT NOT NULL DEFAULT 1;
ALTER TABLE tbl_quest ADD COLUMN IF NOT EXISTS active      BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE tbl_quest ADD COLUMN IF NOT EXISTS repeat_type VARCHAR(20) NULL DEFAULT 'DAILY';
ALTER TABLE tbl_quest MODIFY COLUMN repeat_type VARCHAR(20) NULL DEFAULT 'DAILY';

-- 일일 퀘스트 시드 (없을 때만)
INSERT INTO tbl_quest
    (title, description, type, repeat_type, difficulty, theme, reward, urgency, due_days, active)
SELECT title, description, type, repeat_type, difficulty, theme, reward, urgency, due_days, active
FROM (
    SELECT '기저귀 교대' AS title, '오늘 기저귀 교대를 1회 이상 해주세요' AS description,
           'DAILY' AS type, 'DAILY' AS repeat_type, 'EASY' AS difficulty, 'CARE' AS theme,
           10 AS reward, 1 AS urgency, 1 AS due_days, TRUE AS active
    UNION ALL SELECT '아이와 10분 놀아주기', '집중해서 아이와 10분 놀아주세요',
           'DAILY', 'DAILY', 'EASY', 'ACTIVITY', 15, 1, 1, TRUE
    UNION ALL SELECT '목욕 준비 돕기', '목욕 준비물을 챙겨 도와주세요',
           'DAILY', 'DAILY', 'MEDIUM', 'CARE', 20, 1, 1, TRUE
    UNION ALL SELECT '수유/이유식 챙기기', '수유 또는 이유식 한 끼를 담당해주세요',
           'DAILY', 'DAILY', 'MEDIUM', 'CARE', 20, 1, 1, TRUE
    UNION ALL SELECT '잠자리 루틴', '재우기 전 루틴을 함께 진행해주세요',
           'DAILY', 'DAILY', 'EASY', 'CARE', 15, 1, 1, TRUE
    UNION ALL SELECT '짧은 산책', '유모차 또는 아기띠로 짧게 산책하세요',
           'DAILY', 'DAILY', 'EASY', 'ACTIVITY', 15, 1, 1, TRUE
    UNION ALL SELECT '정리 정돈', '아이 용품을 정리해주세요',
           'DAILY', 'DAILY', 'EASY', 'CARE', 10, 1, 1, TRUE
    UNION ALL SELECT '칭찬 한마디', '배우자 또는 아이에게 칭찬을 전해주세요',
           'DAILY', 'DAILY', 'EASY', 'EMOTION', 10, 1, 1, TRUE
) AS seed
WHERE (SELECT COUNT(*) FROM tbl_quest WHERE type = 'DAILY') = 0;

CREATE TABLE IF NOT EXISTS tbl_member_quest (
    id              BIGINT AUTO_INCREMENT,
    member_email    VARCHAR(100) NOT NULL,
    quest_id        BIGINT       NOT NULL,
    status          VARCHAR(20)  NOT NULL DEFAULT 'TODO', -- TODO | DONE | FAILED | EXPIRED
    assigned_date   DATE         NOT NULL,
    due_date        DATE         NULL,
    completed_at    DATETIME     NULL,
    created_by      VARCHAR(100) NULL,                   -- URGENT 생성 배우자
    PRIMARY KEY (id),
    CONSTRAINT fk_mq_member FOREIGN KEY (member_email) REFERENCES tbl_member (email),
    CONSTRAINT fk_mq_quest  FOREIGN KEY (quest_id) REFERENCES tbl_quest (quest_id),
    INDEX idx_mq_member_date (member_email, assigned_date),
    INDEX idx_mq_member_status (member_email, status)
);

ALTER TABLE tbl_member_quest ADD COLUMN IF NOT EXISTS due_date DATE NULL;
ALTER TABLE tbl_member_quest ADD COLUMN IF NOT EXISTS completed_at DATETIME NULL;
ALTER TABLE tbl_member_quest ADD COLUMN IF NOT EXISTS created_by VARCHAR(100) NULL;

CREATE TABLE IF NOT EXISTS tbl_couple (
    couple_id BIGINT AUTO_INCREMENT,
    email1    VARCHAR(100) NOT NULL,
    email2    VARCHAR(100) NOT NULL,
    PRIMARY KEY (couple_id),
    CONSTRAINT fk_couple_email1 FOREIGN KEY (email1) REFERENCES tbl_member (email),
    CONSTRAINT fk_couple_email2 FOREIGN KEY (email2) REFERENCES tbl_member (email),
    UNIQUE KEY uk_couple_pair (email1, email2)
);

-- YSJ - 케어 챌린지 마스터
CREATE TABLE IF NOT EXISTS tbl_challenge (
    challenge_id   BIGINT AUTO_INCREMENT,
    title          VARCHAR(200) NOT NULL,
    description    TEXT,
    target_days    INT NOT NULL,                 -- 7, 14, 30
    success_point  INT NOT NULL DEFAULT 50,
    fail_point     INT NOT NULL DEFAULT 20,      -- 실패 시 차감
    active         BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (challenge_id)
);

-- YSJ - 회원별 챌린지 진행
CREATE TABLE IF NOT EXISTS tbl_member_challenge (
    id                BIGINT AUTO_INCREMENT,
    member_email      VARCHAR(100) NOT NULL,
    challenge_id      BIGINT NOT NULL,
    status            VARCHAR(20) NOT NULL DEFAULT 'ONGOING', -- ONGOING | SUCCESS | FAILED
    current_streak    INT NOT NULL DEFAULT 0,
    start_date        DATE NOT NULL,
    end_date          DATE NOT NULL,
    last_check_date   DATE NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_mc_member FOREIGN KEY (member_email) REFERENCES tbl_member (email),
    CONSTRAINT fk_mc_chal   FOREIGN KEY (challenge_id) REFERENCES tbl_challenge (challenge_id)
);

-- YSJ - 챌린지 일일 체크인
CREATE TABLE IF NOT EXISTS tbl_challenge_checkin (
    id                    BIGINT AUTO_INCREMENT,
    member_challenge_id   BIGINT NOT NULL,
    check_date            DATE NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_check (member_challenge_id, check_date),
    CONSTRAINT fk_check_mc FOREIGN KEY (member_challenge_id) REFERENCES tbl_member_challenge (id)
);

-- YSJ - 회원 포인트
CREATE TABLE IF NOT EXISTS tbl_member_point (
    member_email VARCHAR(100) NOT NULL,
    point        INT NOT NULL DEFAULT 0,
    PRIMARY KEY (member_email),
    CONSTRAINT fk_point_member FOREIGN KEY (member_email) REFERENCES tbl_member (email)
);

-- YSJ - 포인트 적립/차감 로그
CREATE TABLE IF NOT EXISTS tbl_point_log (
    id           BIGINT AUTO_INCREMENT,
    member_email VARCHAR(100) NOT NULL,
    amount       INT NOT NULL,              -- +적립 / -차감
    reason       VARCHAR(100) NOT NULL,     -- QUEST | CHALLENGE_SUCCESS | CHALLENGE_FAIL | MONTHLY
    ref_id       BIGINT NULL,
    created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_point_log_member (member_email, created_at)
);

-- YSJ - 월간 부부 대결 결과
CREATE TABLE IF NOT EXISTS tbl_monthly_result (
    id             BIGINT AUTO_INCREMENT,
    couple_id      BIGINT NOT NULL,
    month_key     CHAR(7) NOT NULL,        -- 2026-08
    winner_email   VARCHAR(100) NULL,       -- null + is_draw=true 면 공동
    is_draw        BOOLEAN NOT NULL DEFAULT FALSE,
    email1_point   INT NOT NULL,
    email2_point   INT NOT NULL,
    popup_shown1   BOOLEAN NOT NULL DEFAULT FALSE,
    popup_shown2   BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id),
    UNIQUE KEY uk_couple_month (couple_id, month_key),
    CONSTRAINT fk_monthly_couple FOREIGN KEY (couple_id) REFERENCES tbl_couple (couple_id)
);

-- YSJ - 승리 혜택 쿠폰 마스터
CREATE TABLE IF NOT EXISTS tbl_coupon (
    coupon_id   BIGINT AUTO_INCREMENT,
    title       VARCHAR(100) NOT NULL,
    description VARCHAR(300),
    active      BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (coupon_id)
);

-- YSJ - 회원 보유 쿠폰
CREATE TABLE IF NOT EXISTS tbl_member_coupon (
    id           BIGINT AUTO_INCREMENT,
    member_email VARCHAR(100) NOT NULL,
    coupon_id    BIGINT NOT NULL,
    month_key    CHAR(7) NOT NULL,
    status       VARCHAR(20) NOT NULL DEFAULT 'UNUSED', -- UNUSED | USED
    issued_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    used_at      DATETIME NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_mcoupon_member FOREIGN KEY (member_email) REFERENCES tbl_member (email),
    CONSTRAINT fk_mcoupon_coupon FOREIGN KEY (coupon_id) REFERENCES tbl_coupon (coupon_id)
);

-- YSJ - 케어 챌린지 예시 데이터
INSERT INTO tbl_challenge (title, description, target_days, success_point, fail_point, active)
SELECT t.title, t.description, t.target_days, t.success_point, t.fail_point, t.active
FROM (
    SELECT '7일 연속 양치시키기' AS title, '매일 아이 양치 케어' AS description, 7 AS target_days, 50 AS success_point, 20 AS fail_point, TRUE AS active
    UNION ALL SELECT '30일 연속 육아일기', '매일 육아일기 작성', 30, 150, 40, TRUE
    UNION ALL SELECT '14일 연속 산책', '매일 아이와 산책', 14, 80, 25, TRUE
    UNION ALL SELECT '일주일 TV 없이 놀아주기', 'TV 없이 함께 놀이', 7, 60, 20, TRUE
) AS t
WHERE (SELECT COUNT(*) FROM tbl_challenge) = 0;

-- YSJ - 승리 혜택 쿠폰 예시 데이터
INSERT INTO tbl_coupon (title, description, active)
SELECT t.title, t.description, t.active
FROM (
    SELECT '오늘 설거지 면제권' AS title, '오늘 설거지 스킵' AS description, TRUE AS active
    UNION ALL SELECT '영화 선택권', '오늘 볼 영화 결정', TRUE
    UNION ALL SELECT '야식 선택권', '야식 메뉴 결정', TRUE
    UNION ALL SELECT '주말 외출 코스 결정권', '주말 코스 결정', TRUE
    UNION ALL SELECT '커피 한 잔 얻기', '커피 한 잔 받기', TRUE
    UNION ALL SELECT '안마 15분 받기', '안마 15분', TRUE
    UNION ALL SELECT '게임 2시간 허용', '게임 2시간 허용', TRUE
) AS t
WHERE (SELECT COUNT(*) FROM tbl_coupon) = 0;
-- YSJ끝

-- LJW 시작
CREATE TABLE IF NOT EXISTS tbl_market_item (
                                               item_no        BIGINT AUTO_INCREMENT,
                                               seller_email   VARCHAR(100)  NOT NULL,
    title          VARCHAR(100)  NOT NULL,
    price          INT           NOT NULL DEFAULT 0,
    description    VARCHAR(2000),
    trade_type     VARCHAR(10)   NOT NULL,
    category       VARCHAR(30)   NOT NULL,
    age_range      VARCHAR(30),
    `condition`    VARCHAR(20),
    allow_offer    BOOLEAN       NOT NULL DEFAULT FALSE,
    status         VARCHAR(20)   NOT NULL DEFAULT '거래가능',
    location_name  VARCHAR(100),
    latitude       DECIMAL(10,7),
    longitude      DECIMAL(10,7),
    view_count     INT           NOT NULL DEFAULT 0,
    recall_checked BOOLEAN       NOT NULL DEFAULT FALSE,
    recall_flag    BOOLEAN       NOT NULL DEFAULT FALSE,
    bump_at        DATETIME,
    del_flag       BOOLEAN       NOT NULL DEFAULT FALSE,
    reg_time       DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mod_time       DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (item_no),
    CONSTRAINT fk_market_item_seller FOREIGN KEY (seller_email) REFERENCES tbl_member (email)
    );

CREATE TABLE IF NOT EXISTS tbl_market_item_image (
                                                     item_no   BIGINT       NOT NULL,
                                                     file_name VARCHAR(200) NOT NULL,
    ord       INT          NOT NULL DEFAULT 0,
    CONSTRAINT fk_market_item_image_item FOREIGN KEY (item_no) REFERENCES tbl_market_item (item_no)
    );

CREATE TABLE IF NOT EXISTS tbl_market_profile (
                                                  email             VARCHAR(100)  NOT NULL,
    manner_temp       DECIMAL(4,1)  NOT NULL DEFAULT 36.5,
    location_name     VARCHAR(100),
    latitude          DECIMAL(10,7),
    longitude         DECIMAL(10,7),
    location_verified BOOLEAN       NOT NULL DEFAULT FALSE,
    PRIMARY KEY (email),
    CONSTRAINT fk_market_profile_email FOREIGN KEY (email) REFERENCES tbl_member (email)
    );

CREATE TABLE IF NOT EXISTS tbl_rental_detail (
                                                 item_no  BIGINT NOT NULL,
                                                 deposit  INT    NOT NULL DEFAULT 0,
                                                 min_days INT,
                                                 max_days INT,
                                                 PRIMARY KEY (item_no),
    CONSTRAINT fk_rental_detail_item FOREIGN KEY (item_no) REFERENCES tbl_market_item (item_no)
    );

CREATE TABLE IF NOT EXISTS tbl_wish (
                                        wno          BIGINT AUTO_INCREMENT,
                                        item_no      BIGINT       NOT NULL,
                                        member_email VARCHAR(100) NOT NULL,
    reg_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (wno),
    CONSTRAINT fk_wish_item FOREIGN KEY (item_no) REFERENCES tbl_market_item (item_no),
    CONSTRAINT fk_wish_member FOREIGN KEY (member_email) REFERENCES tbl_member (email),
    CONSTRAINT uq_wish UNIQUE (item_no, member_email)
    );

CREATE TABLE IF NOT EXISTS tbl_chat_room (
                                             room_no      BIGINT AUTO_INCREMENT,
                                             item_no      BIGINT       NOT NULL,
                                             buyer_email  VARCHAR(100) NOT NULL,
    seller_email VARCHAR(100) NOT NULL,
    reg_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (room_no),
    CONSTRAINT fk_chat_room_item FOREIGN KEY (item_no) REFERENCES tbl_market_item (item_no),
    CONSTRAINT fk_chat_room_buyer FOREIGN KEY (buyer_email) REFERENCES tbl_member (email),
    CONSTRAINT fk_chat_room_seller FOREIGN KEY (seller_email) REFERENCES tbl_member (email)
    );

CREATE TABLE IF NOT EXISTS tbl_chat_message (
                                                msg_no       BIGINT AUTO_INCREMENT,
                                                room_no      BIGINT       NOT NULL,
                                                sender_email VARCHAR(100) NOT NULL,
    msg_type     VARCHAR(10)  NOT NULL DEFAULT 'TEXT',
    content      VARCHAR(1000),
    offer_price  INT,
    offer_status VARCHAR(10),
    reg_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (msg_no),
    CONSTRAINT fk_chat_message_room FOREIGN KEY (room_no) REFERENCES tbl_chat_room (room_no),
    CONSTRAINT fk_chat_message_sender FOREIGN KEY (sender_email) REFERENCES tbl_member (email)
    );

CREATE TABLE IF NOT EXISTS tbl_review (
                                          review_no    BIGINT AUTO_INCREMENT,
                                          item_no      BIGINT,
                                          writer_email VARCHAR(100) NOT NULL,
    target_email VARCHAR(100) NOT NULL,
    rating       INT          NOT NULL,
    content      VARCHAR(500),
    reg_time     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (review_no),
    CONSTRAINT fk_review_item FOREIGN KEY (item_no) REFERENCES tbl_market_item (item_no),
    CONSTRAINT fk_review_writer FOREIGN KEY (writer_email) REFERENCES tbl_member (email),
    CONSTRAINT fk_review_target FOREIGN KEY (target_email) REFERENCES tbl_member (email)
    );
-- LJW 끝
